### ISSUE TITLE
In the enrollment module, Add an option to add negative criterias

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#18]
While it can be done now, it could become complex to manage when the criteria list grows. We can add another field where we can define the domain of the excluding criteria. 
We then merge the inclusion and exclusion domains this way:
INCLUSION AND NOT EXCLUSION
in the query

**Comment by gonzalesedwin1123** [comment]
I will work on this now.

**Comment by adriancris** [comment]
@reichie020212 to update the code in spp_programs_sp module since the code in this ticket is also affected to the code changes made when I reported about the error in tag-based and sql-based

**Comment by adriancris** [comment]
QA Passed.
Working as expected.
