### ISSUE TITLE
Implement dedup managers

### ISSUE THREAD

**Issue by emjay0921** [openspp-project/openspp-program#4]

**Comment by jeremi** [comment]
@emjay0921 where can I find the code?

**Comment by emjay0921** [comment]
It was already merged to [openg2p-program](https://github.com/OpenG2P/openg2p-program) - 15.0 Branch. Here is the [deduplication_manager.py](https://github.com/OpenG2P/openg2p-program/blob/15.0/g2p_programs/models/managers/deduplication_manager.py)

**Comment by jeremi** [comment]
Make the tests more readable by adding helper functions that prepare the data.
Add tests for this if it is not done yet:
- [x] Same ID number but different ID type
- [x] Same ID number and type but for one it is at the group level, the other at the individual
- [x] Same ID number and type at the group level
- [x] Same ID number and type at the individual group level

**Comment by gonzalesedwin1123** [comment]
I am using the job queue in the dedup function call

**Comment by jeremi** [comment]
We should be able to run it without a task queue as well.
For example, when I add 1 group (or few) to the group, I want to be able to run dedup on this person with the whole group.

**Comment by emjay0921** [comment]
https://github.com/OpenG2P/openg2p-program/pull/1
