### ISSUE TITLE
Program approval receipt (PDF document of what was approved)

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#82]
### **How to Use:**

1. Go to Program
2. Check a record or list of records
3. Click "Program Approval Receipt" button under the "Print" Action Menu then a PDF will be downloaded.
4. Open the PDF.

**Comment by dasunhegoda** [comment]
@jeremi : We will need to identify the template for the PDF for this but the functionality we have already implemented.

**Comment by adriancris** [comment]
QA Passed
Functionality is working as expected but template for the PDF needs to be identified

TSOS-110 : Print Single Program Receipt
TSOS-111 : Print Multiple Program Receipt
