### ISSUE TITLE
Implement different way to associate service points to entitlements

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#83]
When a program is created, we need to be able to define how an entitlement is associated with a service point, if necessary.

For clarifications:
- Link service points to registrants - add a field in the registrant model to identify the assigned service point.
- Copy the service point assigned to the registrant when generating entitlements

**Comment by dasunhegoda** [comment]
- The service points will be at the program-level
- The service points can be a top-up retailer

**Comment by gonzalesedwin1123** [comment]
Is this an ACF specific feature @jeremi @dasunhegoda ?

**Comment by dasunhegoda** [comment]
At 1st, it's ACF specific, then to general OpenSPP if suitable.

**Comment by gonzalesedwin1123** [comment]
Currently, this only provides a way to specify if service points with disabled and inactive contracts can be added to entitlements during generation.

**Comment by dasunhegoda** [comment]
Hi @jeremi 

1. Could you please elaborate more on the different approaches we should take? 
2. Do we need a config to associate service points differently?

**Comment by adriancris** [comment]
QA Passed
Working as expected

**Comment by adriancris** [comment]
tested and approved without comments
