### ISSUE TITLE
Add a new enrollment manager that is based on tag+Area

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#86]
The program will implement a new eligibility manager named TagBasedEligibilityManager. It will inherit from BaseEligibilityManager and will determine eligibility based on a registrant's tag and their association with a specific area, including all of its child areas. The system will prevent any infinite recursion within the area hierarchy. If both tag and area criteria are specified, a registrant must meet both to be considered eligible.

The new manager will be responsible for enrolling and importing registrants, ensuring the new eligibility criteria are upheld during both processes. To optimize performance with potentially large datasets, the manager will utilize pagination or batching techniques during these operations.

### **How to Use:**

**1. Define the Tag eligibility criteria during program creation:**
- Go to Programs menu then click the "Create Program" button.
- In the "Set Program Settings" popup window specify the "Program Name" and select the "Target Type" (Group or Individual)
- In the "Configure Default Eligibility Criteria" tab select the "Tag-based Eligibility".
- Specify the Tag and Area. Tag is required while Area is optional.
- You can check in Domain the records that matched with the selected Target Type, Tags, and Area.
- Proceed with the creation of the new program.

**2. Modify the Tag-based eligibility criteria**
- Go to Programs menu.
- Open the program that will be modified from the list.
- In the program interface click the "Configuration" tab.
- Click the green button in the left of the "Tags Manager" eligibility managers.
- In the popup window click the "Edit" button.
- All editable fields can be modified.
- Click the "Save" button.

**After defining or modifying the Tag-based eligibility criteria, the beneficiaries must be re-validated.** 
- Click the "Import Eligible Registrants" button if you think that there are additional beneficiaries that needs to be added to the program based on the Tag-based eligibility defined.
- Click the "Enroll Eligible Registrants" button to run the Tag-based eligibility criteria checking with the existing registrants. All registrants that are not qualified will be marked us "Not Eligible"

**Comment by reichie020212** [comment]
Done adding the Tag-based eligibility Manager.

Now creating/updating the test cases

**Comment by adriancris** [comment]
Findings: All test cases below are passed and approved by QA

TSOS-45 : Input an Invalid Tag in Program Creation
TSOS-46 : Enroll Individuals Based on Valid Tags only
TSOS-83 : Enroll Groups Based on Valid Tags only
TSOS-84 : Enroll Individuals Based on Valid Tags and Areas
TSOS-47 : Enroll Groups Based on Valid Tags and Areas
TSOS-89 : Correct Number of Records Based on Tag and Target Type

All working as expected
