### ISSUE TITLE
implement a SQL eligibility manager

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#89]
- We should put the specified SQL query in a subquery; that way, we can enforce the type of registrant (group, individual)
- Add a way to test the query and return the number of matching beneficiaries
- Make it work when we re-calculate the eligibility or import new beneficiaries

### Change Logs:
1. Do not allow DMLs in the user-defined SQL query.
2. Fix error in the title bar of the wizard. It is no longer resetting to "Odoo" on any button click action.

### How to use:
**1. Define the SQL eligibility criteria during program creation:**
- Go to Programs menu then click the "Create Program" button.
- In the "Set Program Settings" popup window specify the "Program Name" and select the "Target Type" (Group or Individual)
- In the "Configure Default Eligibility Criteria" tab select the "SQL-base Eligibility".
- Specify the SQL query in the "SQL Query" text box.
- Click the "Validate Query" button.
  - The query validation must return "Valid" for the program to be created. The total number of beneficiaries will also be presented in the UI. 
- Proceed with the creation of the new program.

**2. Modify the SQL eligibility criteria:**
- Go to Programs menu.
- Open the program that will be modified from the list.
- In the program interface click the "Configuration" tab.
- Click the green button in the left of the "SQL Query" eligibility managers.
- In the popup window click the "Edit" button.
- All editable fields can be modified.
- If the "SQL Query" field was modified the "Validate Query" button must be clicked.
  - The query validation must return "Valid", otherwise the beneficiary enrollment will fail. The total number of beneficiaries will also be presented in the UI. 
- Click the "Save" button.

**After defining or modifying the SQL eligibility criteria, the beneficiaries must be re-validated.** 
- Click the "Import Eligible Registrants" button if you think that there are additional beneficiaries that needs to be added to the program based on the SQL Query defined.
- Click the "Enroll Eligible Registrants" button to run the SQL eligibility criteria checking with the existing registrants. All registrants that are not qualified will be marked us "Not Eligible"

**Comment by gonzalesedwin1123** [comment]
Working on enhancing the query to support filtering based on registrant type (group/individual)

**Comment by gonzalesedwin1123** [comment]
Completed the testing. Preparing the automated test and PR.

**Comment by gonzalesedwin1123** [comment]
Create program wizard with the SQL eligibility manager:


![Image](https://github.com/OpenSPP/openspp-program/assets/87359145/3911f062-bf58-43cf-85ef-0e0d5d54e3db)

**Comment by gonzalesedwin1123** [comment]
Adding more automated test to increase the coverage.

**Comment by adriancris** [comment]
@gonzalesedwin1123 to modify the Query Validation Message when the SQL Query is valid but returns zero record

**Comment by adriancris** [comment]
Findings: All test cases below are passed and approved by QA

TSACF-40: Input an Invalid SQL Query
TSACF-46: Input a No Record, Valid SQL Query
TSACF-43: Enroll Individuals Based on Valid SQL Query
TSACF-47: Enroll Groups Based on Valid SQL Query

All working as expected

**Comment by gonzalesedwin1123** [comment]
Resetting this to "In Progress" because of issue with DMLs can be executed in the SQL query.

**Comment by gonzalesedwin1123** [comment]
@adriancris the issue with the changing of the popup window's title to "Odoo" is now fixed. Please check. The checking and preventing DMLs (insert, update, delete) are now in the code.

**Comment by adriancris** [comment]
QA Passed
- "Set Program Settings" window title becomes "Odoo" after clicking Validate Query - FIXED
- DMLs return an error when run - PASSED
