### ISSUE TITLE
Initialize the database without demo data

### ISSUE THREAD

**Issue by jeremi** [openspp-project/openspp-program#92]
The main issue we aim to address is the undesired loading of demo items in the Odoo stock management module, company, accounting, users, and others, which we aim to achieve without modifying the core code of Odoo. 

To achive this, we need to disable the creation of demo data during database initialization.

### **How to use:**

**1. Clone spp docker repo.**
- Open your terminal then go to your selected directory to clone spp docker
- Enter this command to clone: "git clone https://github.com/OpenSPP/openspp-docker.git"
- Check if openspp-docker directory is now showing in your current directory

**2. Invoke Commands**
- Open your terminal then go to openspp-docker directory
- Enter these commands in order:
-- invoke develop
-- invoke img-pull
-- invoke img-build --pull
-- invoke git-aggregate
-- invoke resetdb
-- invoke start
- In "invoke resetdb" command, the initialized database is configured without demo data. To include demo data in add "--demo" in the command.
-- invoke resetdb --demo

**3. Accessing application**
- Odoo: http://localhost:15069/
- Mailhog: http://localhost:15025/
- wdb: http://localhost:15984/
- pgweb: http://localhost:15081/

**Comment by gonzalesedwin1123** [comment]
@reichie020212 Please provide informations here for the DevOps

**Comment by reichie020212** [comment]
The default of command "invoke resetdb" is now changed to initializing database without demo data

to initilize a database with demo demo, you need to add option "--demo" in the command. "invoke resetdb --demo"

**Comment by jeremi** [comment]
This seems good. Has it been verified?
